### ISSUE TITLE
After v0.10.0 release the render is blank and showing warning

### ISSUE THREAD

**Issue by orther** [uptrend-tech/uptrend-redux-modules#42]
>Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.
>
> Connect(ResourceLoader) uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
>  componentWillReceiveProps
>  componentWillUpdate
>
> The above lifecycles should be removed. Learn more about this warning here:
>https://fb.me/react-async-component-lifecycle-hooks

**Comment by dyyylan** [comment]
The network request is completed successfully but none of the resource actions are ever fired (not even the initial load)

**Comment by orther** [comment]
Solved by setting to re-render after every parent render 13d76e3734abd333b9097066b74832bd38404826
